---

#name: Packer syntax validate
#
#on:
#  pull_request:
#    branches:
#      - main
#
#jobs:
#  packer:
#    runs-on: ubuntu-latest
#    name: packer
#
#    steps:
#      - name: Checkout Repository
#        uses: actions/checkout@v2
#
#      - name: Validate Template
#        uses: hashicorp/packer-github-actions@master
#        with:
#          command: validate
#          arguments: -syntax-only
#          target: packer.pkr.hcl
#
#      # build artifact
#     # - name: Build Artifact
#     #   uses: hashicorp/packer-github-actions@master
#     #   with:
#     #     command: build
#     #     arguments: "-color=false -on-error=abort"
#     #     target: packer.pkr.hcl
#     #   env:
#     #     PACKER_LOG: 1
#
#
